version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avito
    restart: always
    ports:
      - "5432:5432"
#    volumes:
#      - ./db/:/var/lib/postgresql/data

volumes:
  postgres_data: